version: 2
jobs:
  deps:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-cache-{{ checksum "requirements-ci.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-ci.txt
      - save_cache:
          key: deps-cache-{{ checksum "requirements-ci.txt" }}
          paths:
            - venv
  linters:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-cache-{{ checksum "requirements-ci.txt" }}
      - run:
          command: |
            python3 -m venv venv
      - run:
          command: |
            . venv/bin/activate
            export PACKAGES=$(python -c "from setuptools import find_packages; print(' '.join({p.split('.')[0] + '/' for p in find_packages()}))")
            isort --check-only
            pylint -v --output-format=parseable $PACKAGES -j 0
            flake8 --config=".flake8" 
  tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-cache-{{ checksum "requirements-ci.txt" }}
      - run:
          command: |
            python3 -m venv venv
      - run:
          command: |
            . venv/bin/activate
            pytest --cov=./ -s -v
            codecov --token=$CODECOV_TOKEN
            isort -y
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers =" >> ~/.pypirc
            echo -e "  pypi" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository=https://pypi.python.org/pypi" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            . venv/bin/activate
            python setup.py sdist upload -r pypi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deps
      - linters:
          requires:
            - deps
      - tests:
          requires:
            - linters
      - deploy:
          requires:
            - tests
          filters:
            branches:
              only: master